### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ottok**

### CODE REVIEW

**Comment by ottok** [comment]
Ping @janlindstrom or @temeo ?

**Comment by ottok** [comment]
Please merge @temeo

**Comment by ottok** [comment]
Please merge @temeo

**Comment by ottok** [comment]
Please merge @temeo

**Review by abychko — APPROVED** [review]

**Comment by temeo** [comment]
@ottok Made corresponding typo fixes in all branches v25 -> v26 -> master. Please check if this still needed.

**Comment by ottok** [comment]
Fixed via ecee5b3bc54c1fdfcf13ac8a3c8ea67bfbf82ef9 and bac1c07f02288e4218707b9ecef891b029edc0d4

**Pull request closed without merging**
